-- ───────────────────────────────────────────────────────────────────────────
-- MÓDULO EVENTOS — esquema próprio, não exposto ao PostgREST
--
-- Por que schema separado e não `public` com prefixo: o módulo fala Postgres
-- DIRETO pelo pooler (decisão 0003), não pelo cliente Supabase. A restrição
-- que obriga `ciclo_*` a viver em `public` — o PostgREST só embute relação
-- dentro do schema ativo — não se aplica a quem não usa PostgREST. Ver a
-- decisão 0007.
--
-- IDs INTEIROS, PRESERVADOS da origem. Número de pedido e de voucher já
-- circularam em e-mail e em comprovante impresso; trocá-los por uuid
-- quebraria a conferência no balcão de um evento que já aconteceu. Só a
-- PESSOA é uuid, porque ela é da plataforma, não deste módulo.
--
-- Dinheiro em centavos, inteiro. A origem usa DECIMAL(10,2); a conversão
-- acontece na carga, uma vez, em vez de arredondar a cada soma.
-- ───────────────────────────────────────────────────────────────────────────

create schema if not exists eventos;

-- ── Quem conduz o evento ───────────────────────────────────────────────────
-- Orientador aqui é a pessoa pública que conduz a atividade — foto e bio saem
-- no material de divulgação. ⚠️ Não se confunde com o papel `orientador` do
-- Ciclo, que é autorização. Nomes iguais, domínios diferentes.
create table eventos.orientadores (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  pessoa_id     uuid references public.pessoas(id) on delete set null,
  nome          text not null,
  foto_url      text,
  bio           text,
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now()
);

-- ── Evento ─────────────────────────────────────────────────────────────────
create table eventos.eventos (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  nome          text not null,
  slug          text unique,
  data_inicial  date not null,
  data_final    date not null,

  -- ONDE acontece. Aponta para o catálogo comum: Academia, hotel, salão.
  local_id      uuid references public.locais(id) on delete set null,

  -- QUEM promove — e portanto em qual conta Cielo o dinheiro cai. É o mesmo
  -- trio de `public.credenciais` (decisão 0010), de propósito: a conta é da
  -- entidade, e o evento herda dela. Um `conta_cielo_id` no evento, como fazia
  -- a origem, deixaria dois eventos da mesma Regional apontando para contas
  -- diferentes sem ninguém perceber.
  --
  -- ⚠️ Anulável enquanto a carga não conciliar os `Promotor` antigos — que
  -- eram nome e telefone em texto, sem vínculo com a estrutura. Até lá o
  -- evento não vende, e a tela diz isso.
  promotor_organizacao_id uuid references public.organizacoes(id) on delete restrict,
  promotor_unidade_id     uuid references public.unidades(id)     on delete restrict,
  promotor_local_id       uuid references public.locais(id)       on delete restrict,

  ativo         boolean not null default true,

  -- Personalização do voucher. `mostrar` é jsonb porque são cinco chaves
  -- booleanas que só a tela do voucher lê — cinco colunas fariam a tabela
  -- crescer sem que nada além dela as consultasse.
  voucher_banner_url     text,
  voucher_logo_url       text,
  voucher_cor_primaria   text not null default '#132460',
  voucher_cor_secundaria text not null default '#B45309',
  voucher_boas_vindas    text,
  voucher_instrucoes     text,
  voucher_rodape         text,
  voucher_mostrar        jsonb not null default
    '{"participante":true,"evento":true,"ingresso":true,"qrcode":true,"pagamento":true}'::jsonb,

  landing       jsonb not null default '{}'::jsonb,
  migracao_extras jsonb,

  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),

  constraint datas_coerentes check (data_final >= data_inicial),
  constraint promotor_unico check (
    (case when promotor_organizacao_id is not null then 1 else 0 end
   + case when promotor_unidade_id     is not null then 1 else 0 end
   + case when promotor_local_id       is not null then 1 else 0 end) <= 1
  )
);

create index idx_eventos_periodo on eventos.eventos (data_inicial desc) where ativo;

create table eventos.evento_orientadores (
  evento_id     integer not null references eventos.eventos(id) on delete cascade,
  orientador_id integer not null references eventos.orientadores(id) on delete cascade,
  ordem         smallint not null default 0,
  primary key (evento_id, orientador_id)
);

-- ── O que se vende ─────────────────────────────────────────────────────────
create table eventos.ingresso_tipos (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  evento_id     integer not null references eventos.eventos(id) on delete cascade,
  nome          text not null,
  descricao     text,
  valor_centavos integer not null default 0 check (valor_centavos >= 0),
  max_parcelas  smallint not null default 1 check (max_parcelas >= 1),
  -- Nulo = sem limite. A origem tratava nulo como informativo.
  quantidade    integer check (quantidade is null or quantidade >= 0),
  venda_inicio  timestamptz,
  venda_fim     timestamptz,
  idade_min     smallint,
  idade_max     smallint,
  -- Um por CPF: o caso do jantar, em que a pessoa não pode comprar dois.
  unico_por_cpf boolean not null default false,
  -- 'principal' é o ingresso que sozinho dá entrada; 'adicional' só existe
  -- acompanhando um principal (jantar, transporte).
  papel         text not null default 'adicional' check (papel in ('principal','adicional')),
  exige_principal boolean not null default false,
  exibir_venda_publica boolean not null default true,
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now(),
  constraint faixa_etaria check (idade_min is null or idade_max is null or idade_max >= idade_min)
);

create index idx_ingresso_tipos_evento on eventos.ingresso_tipos (evento_id) where ativo;

-- Perguntas que o tipo de ingresso faz na compra. `opcoes` é jsonb porque a
-- lista de escolhas varia de pergunta para pergunta.
create table eventos.ingresso_campos (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  ingresso_tipo_id integer not null references eventos.ingresso_tipos(id) on delete cascade,
  rotulo        text not null,
  tipo          text not null default 'texto'
                  check (tipo in ('texto','numero','data','selecao','multipla','booleano')),
  opcoes        jsonb,
  obrigatorio   boolean not null default false,
  ordem         smallint not null default 0,
  ativo         boolean not null default true
);

create table eventos.combos (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  evento_id     integer not null references eventos.eventos(id) on delete cascade,
  nome          text not null,
  descricao     text,
  valor_centavos integer not null default 0 check (valor_centavos >= 0),
  quantidade    integer,
  venda_inicio  timestamptz,
  venda_fim     timestamptz,
  limite_por_cpf smallint,
  max_parcelas  smallint not null default 1 check (max_parcelas >= 1),
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now()
);

create table eventos.combo_itens (
  id            integer primary key generated by default as identity,
  combo_id      integer not null references eventos.combos(id) on delete cascade,
  ingresso_tipo_id integer not null references eventos.ingresso_tipos(id) on delete restrict,
  quantidade    smallint not null default 1 check (quantidade >= 1),
  unique (combo_id, ingresso_tipo_id)
);

create table eventos.cupons (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  evento_id     integer not null references eventos.eventos(id) on delete cascade,
  codigo        text not null,
  descricao     text,
  tipo          text not null check (tipo in ('percentual','valor')),
  -- Percentual (0..100) ou centavos, conforme `tipo`. O check cobre os dois.
  valor         integer not null check (valor >= 0),
  ingresso_tipo_id integer references eventos.ingresso_tipos(id) on delete cascade,
  combo_id      integer references eventos.combos(id) on delete cascade,
  max_usos_total integer,
  max_usos_por_cpf integer,
  vigencia_inicio timestamptz,
  vigencia_fim  timestamptz,
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now(),
  constraint percentual_ate_cem check (tipo <> 'percentual' or valor <= 100),
  -- ⚠️ Único por evento, e case-insensitive: quem digita o cupom no checkout
  -- não distingue maiúscula de minúscula, e dois cupons que só diferem na
  -- caixa dariam descontos diferentes para o que a pessoa vê como o mesmo
  -- código.
  constraint cupom_codigo_nao_vazio check (length(btrim(codigo)) > 0)
);

create unique index uq_cupom_codigo on eventos.cupons (evento_id, lower(codigo));

-- ── A compra ───────────────────────────────────────────────────────────────
--
-- `pedidos` é a intenção: existe entre o "comprar" e a resposta da Cielo, e
-- guarda os participantes em jsonb porque eles ainda não viraram inscrição.
-- Sem esta tabela, uma queda no meio do pagamento perderia o que a pessoa
-- digitou — e o PIX, que confirma minutos depois, não teria onde esperar.
create table eventos.pedidos (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  comprador_id  uuid not null references public.pessoas(id) on delete restrict,
  comprador_cpf text,
  evento_id     integer not null references eventos.eventos(id) on delete restrict,
  ingresso_tipo_id integer references eventos.ingresso_tipos(id) on delete restrict,
  combo_id      integer references eventos.combos(id) on delete restrict,
  quantidade    smallint not null default 1 check (quantidade >= 1),
  cupom_id      integer references eventos.cupons(id) on delete set null,
  valor_original_centavos integer not null default 0 check (valor_original_centavos >= 0),
  desconto_centavos       integer not null default 0 check (desconto_centavos >= 0),
  participantes jsonb not null default '[]'::jsonb,
  status        text not null default 'pendente'
                  check (status in ('pendente','confirmado','cancelado','expirado')),
  -- Resposta da Cielo em jsonb: order_id, payment_id, método, tid, código de
  -- autorização, bandeira, QR do PIX, código e mensagem de retorno. São doze
  -- colunas na origem, lidas sempre juntas e só pelo fluxo de pagamento.
  cielo         jsonb not null default '{}'::jsonb,
  inscricao_ids integer[],
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_pedidos_status on eventos.pedidos (status, criado_em desc);
create index idx_pedidos_cielo_order on eventos.pedidos ((cielo->>'order_id'));

-- `inscricoes` é o ingresso de uma pessoa. Na origem tinha SESSENTA colunas,
-- porque carrega quatro histórias ao mesmo tempo: a compra, o estorno, a
-- transferência entre eventos e a troca de titular. Aqui elas continuam na
-- mesma linha — separá-las em tabelas exigiria juntar quatro delas para
-- responder "esta pessoa entra?", que é a pergunta do totem de check-in.
create table eventos.inscricoes (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  pessoa_id     uuid not null references public.pessoas(id) on delete restrict,
  evento_id     integer not null references eventos.eventos(id) on delete restrict,
  ingresso_tipo_id integer references eventos.ingresso_tipos(id) on delete restrict,
  combo_id      integer references eventos.combos(id) on delete set null,
  pedido_id     integer references eventos.pedidos(id) on delete set null,
  cupom_id      integer references eventos.cupons(id) on delete set null,

  -- Quem PAGOU, quando não é quem vai. Mãe que compra para a família inteira.
  comprador_id  uuid references public.pessoas(id) on delete set null,
  -- Amarra as linhas da mesma compra: é o que permite estornar o combo
  -- inteiro em vez de ingresso a ingresso.
  compra_grupo_id uuid,

  numero_convite text,
  forma_pagamento text,
  tipo_venda    text not null default 'online'
                  check (tipo_venda in ('online','balcao','importado','cortesia')),
  status        text not null default 'pendente'
                  check (status in ('pendente','pago','cancelado','expirado','transferido')),
  valor_original_centavos integer not null default 0 check (valor_original_centavos >= 0),
  desconto_centavos       integer not null default 0 check (desconto_centavos >= 0),

  data_compra   timestamptz,
  checkin_em    timestamptz,
  qr_code       text,

  -- Rastro de conferência do balcão: o que se confere quando o pagamento não
  -- passou pela Cielo.
  credenciamento_pedido text,
  pix_data      date,
  pix_recibo    text,
  cortesia_motivo text,
  cielo         jsonb not null default '{}'::jsonb,

  -- Cancelamento e estorno. `estorno` em jsonb: valor, forma, comprovante,
  -- quem efetuou e quando — sete colunas que só a tela de estorno lê.
  cancelado_em  timestamptz,
  cancelado_por uuid references public.pessoas(id) on delete set null,
  cancelamento_motivo text,
  cancelamento_ancora_id integer,
  estorno_status text check (estorno_status is null
                  or estorno_status in ('pendente','feito','recusado')),
  estorno       jsonb,

  -- Transferência entre eventos: a inscrição velha fica com status
  -- 'transferido' e aponta para a nova. Não se apaga — o comprovante antigo
  -- circulou, e alguém vai chegar no balcão com ele.
  transferido_para_id integer references eventos.inscricoes(id) on delete set null,
  transferido_de_id   integer references eventos.inscricoes(id) on delete set null,
  transferido_em      timestamptz,
  transferido_por     uuid references public.pessoas(id) on delete set null,

  -- Troca de titular: o ingresso muda de dono, e quem era antes fica
  -- registrado. Sem isto, a pessoa que comprou some do histórico.
  titular_anterior_id uuid references public.pessoas(id) on delete set null,
  titular_trocado_em  timestamptz,
  titular_trocado_por uuid references public.pessoas(id) on delete set null,
  titular_troca_motivo text,

  observacao    text,
  migracao_extras jsonb,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_inscricoes_pessoa on eventos.inscricoes (pessoa_id, evento_id);
create index idx_inscricoes_evento on eventos.inscricoes (evento_id, status);
create index idx_inscricoes_grupo on eventos.inscricoes (compra_grupo_id) where compra_grupo_id is not null;
create index idx_inscricoes_checkin on eventos.inscricoes (evento_id) where checkin_em is not null;
-- ⚠️ Índice para o totem: no check-in se procura pelo número do convite, com
-- fila esperando. Sem ele, cada leitura varre a tabela inteira.
create index idx_inscricoes_convite on eventos.inscricoes (evento_id, numero_convite)
  where numero_convite is not null;

create table eventos.inscricao_respostas (
  id            integer primary key generated by default as identity,
  inscricao_id  integer not null references eventos.inscricoes(id) on delete cascade,
  campo_id      integer references eventos.ingresso_campos(id) on delete set null,
  -- ⚠️ Fotografia do rótulo no momento da compra. O campo pode ser renomeado
  -- depois, e a resposta precisa continuar dizendo a que pergunta respondeu.
  rotulo        text not null,
  valor         text,
  criado_em     timestamptz not null default now()
);

create index idx_respostas_inscricao on eventos.inscricao_respostas (inscricao_id);

-- ── Comprador sem conta (decisão 0005) ─────────────────────────────────────
-- Quem compra ingresso não vira operador do sistema: autentica por link
-- próprio, com prazo, para ver e transferir o que comprou.
--
-- ⚠️ Guarda o HASH, nunca o token. Um vazamento desta tabela entregaria a
-- compra de todo mundo se o valor estivesse em claro.
create table eventos.magic_links (
  id            integer primary key generated by default as identity,
  pessoa_id     uuid not null references public.pessoas(id) on delete cascade,
  token_hash    text not null unique,
  evento_id     integer references eventos.eventos(id) on delete cascade,
  expira_em     timestamptz not null,
  usado_em      timestamptz,
  criado_em     timestamptz not null default now()
);

create index idx_magic_links_validade on eventos.magic_links (expira_em) where usado_em is null;

create table eventos.carrinhos_abandonados (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  evento_id     integer not null references eventos.eventos(id) on delete cascade,
  ingresso_tipo_id integer references eventos.ingresso_tipos(id) on delete set null,
  pessoa_id     uuid references public.pessoas(id) on delete set null,
  nome          text,
  email         text,
  telefone      text,
  cpf           text,
  quantidade    smallint not null default 1,
  convertido    boolean not null default false,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_carrinhos_pendentes on eventos.carrinhos_abandonados (evento_id, criado_em desc)
  where not convertido;

-- ── Comissão organizadora ──────────────────────────────────────────────────
-- Setor e função de quem organiza o evento. ⚠️ Não se confunde com as funções
-- doutrinárias da plataforma: aquelas são progressão institucional, estas
-- valem por um evento só.
create table eventos.comissao_setores_padrao (
  id     integer primary key generated by default as identity,
  nome   text not null unique,
  ordem  smallint not null default 0,
  ativo  boolean not null default true
);

create table eventos.comissao_funcoes_padrao (
  id       integer primary key generated by default as identity,
  setor_id integer references eventos.comissao_setores_padrao(id) on delete cascade,
  nome     text not null,
  ordem    smallint not null default 0,
  ativo    boolean not null default true
);

create table eventos.comissao_membros (
  id         integer primary key generated by default as identity,
  legado_id  integer unique,
  evento_id  integer not null references eventos.eventos(id) on delete cascade,
  pessoa_id  uuid references public.pessoas(id) on delete set null,
  -- Anulável porque a origem gravava setor e função em TEXTO, não como
  -- referência ao catálogo. Conciliar é trabalho de tela.
  nome       text not null,
  setor      text,
  funcao     text,
  criado_em  timestamptz not null default now()
);

create index idx_comissao_evento on eventos.comissao_membros (evento_id);

-- ── Régua de e-mail por evento ─────────────────────────────────────────────
--
-- ⚠️ Isto é a REGRA, não a mensagem. O envio continua passando por
-- `public.notificacoes` — a fila é uma só (regra do AGENTS.md), e um módulo
-- com fila própria significaria duas coisas para monitorar, dois lugares onde
-- uma mensagem pode ficar presa, e nenhuma visão de conjunto.
create table eventos.reguas_email (
  id            integer primary key generated by default as identity,
  legado_id     integer unique,
  evento_id     integer not null references eventos.eventos(id) on delete cascade,
  nome_interno  text not null,
  assunto       text not null,
  corpo         text,
  -- 'data' dispara num instante; 'relativo' N dias antes ou depois do evento.
  agendamento   text not null default 'data' check (agendamento in ('data','relativo')),
  data_envio    timestamptz,
  dias          smallint,
  -- A quem: todos, quem comprou certo tipo, quem fez check-in, quem não fez.
  segmento      text not null default 'todos',
  ingresso_tipo_id integer references eventos.ingresso_tipos(id) on delete cascade,
  anexar_voucher boolean not null default false,
  ativo         boolean not null default true,
  criado_em     timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint agendamento_coerente check (
    (agendamento = 'data'     and data_envio is not null) or
    (agendamento = 'relativo' and dias is not null)
  )
);

-- Quem recebe aviso quando alguém compra. Era `RegionalPromotorEmail`.
create table eventos.avisos_compra (
  id          integer primary key generated by default as identity,
  legado_id   integer unique,
  unidade_id  uuid references public.unidades(id) on delete cascade,
  evento_id   integer references eventos.eventos(id) on delete cascade,
  email       text not null,
  ativo       boolean not null default true,
  criado_em   timestamptz not null default now()
);

-- ── Proteção do checkout público ───────────────────────────────────────────
-- O checkout não exige conta (decisão 0005), então a única barreira contra
-- alguém varrer CPFs é esta.
create table eventos.limites_uso (
  id          bigserial primary key,
  balde       text not null,
  identidade  text not null,
  criado_em   timestamptz not null default now()
);

create index idx_limites_janela on eventos.limites_uso (balde, identidade, criado_em desc);

-- ── RLS ligada, GRANT nenhum ───────────────────────────────────────────────
--
-- O navegador NUNCA fala com estas tabelas: quem fala é o servidor, pelo
-- pooler, e a autorização acontece por capacidade antes de qualquer consulta
-- (decisão 0003). RLS ligada mesmo assim, porque `anon` e `authenticated` não
-- podem alcançar nada nem por engano — e porque uma tabela sem RLS que ganhe
-- GRANT no futuro ficaria aberta em silêncio.
do $$
declare t text;
begin
  for t in select tablename from pg_tables where schemaname = 'eventos' loop
    execute format('alter table eventos.%I enable row level security', t);
    execute format('revoke all on eventos.%I from anon, authenticated', t);
  end loop;
end $$;

revoke usage on schema eventos from anon, authenticated;

comment on schema eventos is
  'Módulo de eventos. Acesso só pelo servidor, via Postgres direto (decisão 0003). Sem GRANT para anon/authenticated.';
